### PR TITLE
MH-22 Review Tutor/Teacher when request closed out.

### LINKED ISSUE #63: MH-22 Review Tutor/Teacher when request closed out.
Task Description:
Set up a way to review teachers when a request is closed out. The student should be able to review the teacher upon request completion whether a direct request or a global request. 

How to Evaluate:

Log in to alice@email.com password and then post a global request. Close out global request. You should not be redirected to review page since no one has accepted the global request yet. Now make global request and have bobby accept the global request. Now sign back in to alice and close out global request. Since bobby is attached to the global request once alice closes the global request she should be redirected to a review page where she can review bobby. You can repeat this process for other users to see if it still works for everyone. 

Grader also needs to go through the evaluation scheme for direct request. Make direct request to any user as alice. If you close out the request you are redirected to review page where you can review teacher. Otherwise you can return to your profile without reviewing.

### PR DESCRIPTION
**Pull request by csunidev**
Closes #63 
Task Outcome:

Now once a student closes out a request they will be redirected to a review page where they can review their teacher. There is a back button to their own user profile if they wish to not review the teacher. If a global request is closed out without a teacher attached (where no user has accepted the global request) the student is redirected back to global request index without review option. 

How to Evaluate:

Log in to alice@email.com password and then post a global request. Close out global request. You should not be redirected to review page since no one has accepted the global request yet. Now make global request and have bobby accept the global request. Now sign back in to alice and close out global request. Since bobby is attached to the global request once alice closes the global request she should be redirected to a review page where she can review bobby. You can repeat this process for other users to see if it still works for everyone.

Grader also needs to go through the evaluation scheme for direct request. Make direct request to any user as alice. If you close out the request you are redirected to review page where you can review teacher. Otherwise you can return to your profile without reviewing.

### CODE REVIEW

**Review by skhalid1120 — APPROVED** [review]
Looks good!

**Review by gkiga — CHANGES_REQUESTED** [review]
The reviews for global requests seemed to work for me! Just 2 thoughts:

1. Will this feature be added to direct requests as well? It only seems to be implemented for global requests.
2. I can still to a user's profile page and click "Add New Review" so maybe this button should be removed.

**Comment by csunidev** [comment]
It is implemented for direct request. Let me know if it isn't showing for you. After making direct request if student closes out request it should redirect to review teacher. Yeah I will remove the button on the profile pages after you confirm whether direct request review works. I'll repush after that. Thanks.

**Review by gkiga — APPROVED** [review]
Ok, it is working for direct requests so that's great! 

Last note, when I look at the review show page, it has "Your Name" for the review sender name. This is somewhat confusing when I am the reviewed user and not the review sender. Is it possible to have this changed to "Reviewer Name" or something similar?

Otherwise, this branch looks good!

**Pull request merged**
